// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoleWeb.DAL;

#nullable disable

namespace RoleWeb.DAL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260608062651_EntityInit")]
    partial class EntityInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupParameterEntityUserGroupEntity", b =>
                {
                    b.Property<string>("ParametersGUID")
                        .HasColumnType("text");

                    b.Property<string>("UserGroupsGUID")
                        .HasColumnType("text");

                    b.HasKey("ParametersGUID", "UserGroupsGUID");

                    b.HasIndex("UserGroupsGUID");

                    b.ToTable("user_groups_parameters", (string)null);
                });

            modelBuilder.Entity("RoleWeb.DAL.Entities.GroupParameterEntity", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("text")
                        .HasColumnName("guid");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NameJSON")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_json");

                    b.Property<string>("ParentGUID")
                        .HasColumnType("text");

                    b.HasKey("GUID");

                    b.HasIndex("ParentGUID");

                    b.ToTable("group_parameters", (string)null);
                });

            modelBuilder.Entity("RoleWeb.DAL.Entities.UserEntity", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("text")
                        .HasColumnName("guid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("GUID");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RoleWeb.DAL.Entities.UserGroupEntity", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("text")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("GUID");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("UserEntityUserGroupEntity", b =>
                {
                    b.Property<string>("UserGroupsGUID")
                        .HasColumnType("text");

                    b.Property<string>("UsersGUID")
                        .HasColumnType("text");

                    b.HasKey("UserGroupsGUID", "UsersGUID");

                    b.HasIndex("UsersGUID");

                    b.ToTable("user_user_groups", (string)null);
                });

            modelBuilder.Entity("GroupParameterEntityUserGroupEntity", b =>
                {
                    b.HasOne("RoleWeb.DAL.Entities.GroupParameterEntity", null)
                        .WithMany()
                        .HasForeignKey("ParametersGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoleWeb.DAL.Entities.UserGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("UserGroupsGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleWeb.DAL.Entities.GroupParameterEntity", b =>
                {
                    b.HasOne("RoleWeb.DAL.Entities.GroupParameterEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentGUID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("UserEntityUserGroupEntity", b =>
                {
                    b.HasOne("RoleWeb.DAL.Entities.UserGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("UserGroupsGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoleWeb.DAL.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
